name: Release IPNetDB-Service

env:
  IMAGE_NAME: ipnetdb-service

on:
  release:
    types: [published]

jobs:
  containerise:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - uses: docker/build-push-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into GitHub Container Registry
      run: docker login https://ghcr.io -u ${{ github.actor }} -p ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: true
        tags: ghcr.io/meeb/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        cache-from: type=registry,ref=ghcr.io/meeb/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        cache-to: type=inline
        build-args: |
          IMAGE_NAME=${{ env.IMAGE_NAME }}
